# --- Data Paths ---

DATA_DIR: "data/"                       # Base data folder
IMAGE_DIR: "data/mimic-cxr-jpg-2.0.0/files/"  # Where chest X-ray JPGs are stored
CSV_PATH: "data/splits/master_subset_2k.csv"  # CSV with image paths + labels

# --- Output Paths ---
OUTPUT_DIR: "outputs/cdiag/"            # Folder to save logs, checkpoints
MODEL_NAME: "best_cdiag.pth"            # File name for best model weights

# --- Model & Training Hyperparameters ---
IMG_SIZE: 256                           # Resize images to this square size
BATCH_SIZE: 16                          # # of images per training step
EPOCHS: 15                              # How many times the dataset is seen
LEARNING_RATE: 0.0001                   # Optimizer step size (smaller = safer)

# --- System ---
DEVICE: "cuda"                           # Use "cuda" if GPU available
NUM_WORKERS: 4                          # How many parallel workers load data
