# Configuration for training the main CAF-GAN

# --- Data Paths ---
IMAGE_DIR: "/content/drive/MyDrive/CAF-GAN/mimic-cxr-jpg-2.0.0/files/"
TRAIN_CSV_PATH: "/content/drive/MyDrive/CAF-GAN/data/splits/train.csv"
CDIAG_PATH: "/content/drive/MyDrive/CAF-GAN/outputs/cdiag/best_cdiag_colab.pth"
CSEG_PATH: "/content/drive/MyDrive/CAF-GAN/outputs/cseg/best_cseg_colab.pth"

# --- Output Paths ---
OUTPUT_DIR: "/content/drive/MyDrive/CAF-GAN/outputs/gan/"
IMAGE_OUTPUT_DIR: "/content/drive/MyDrive/CAF-GAN/outputs/gan/generated_images/"

# --- Model & Training Hyperparameters ---
"IMG_SIZE": 256,
"CHANNELS": 3,
"LATENT_DIM": 128,
"BATCH_SIZE": 16,  # GANs are memory intensive
"EPOCHS": 200,     # GANs need many epochs to converge
"G_LR": 0.0001,       # ⬅️ Optimized for your critic strengths
"D_LR": 0.0001,       # ⬅️ Balanced with generator
"B1": 0.5,
"B2": 0.999,
"N_CRITIC": 5,        # ⬅️ Standard WGAN-GP value

# --- Loss Weights (CALIBRATED for your critic performance) ---
"LAMBDA_GP": 10,
"LAMBDA_FAIR": 0.15,   # ⬅️ Increased slightly (Cdiag: 66% accuracy)
"LAMBDA_CLINIC": 0.08, # ⬅️ Increased slightly (Cseg: 57.6% Dice)

# --- Adaptive Training Parameters ---
"USE_GRADIENT_CLIPPING": True,
"MAX_GRAD_NORM": 1.0,
"LR_DECAY_FACTOR": 0.8,
"LR_DECAY_PATIENCE": 10,

# --- System & Logging ---
"DEVICE": cuda,
"NUM_WORKERS": 2,
"LOG_FREQ": 50,
"SAVE_IMG_FREQ": 1,
"SAVE_MODEL_FREQ": 10,